version: '3'
services:
  backend:
    build: 
      context: ..
      dockerfile: /home/jakub/Pulpit/PROJEKT-DDD/ALL/back.dockerfile
    ports:
     - "8080:80"
  frontend:
    build: 
      context: ..
      dockerfile: /home/jakub/Pulpit/PROJEKT-DDD/ALL/front.dockerfile
    ports:
     - "8000:80"
#docker-compose -p docker up --build